#!/usr/bin/env ruby

# theres needs to be a dragon in the game
#                                                  /===-_---~~~~~~~~~------____
#                                                 |===-~___                _,-'
#                  -==\\                         `//~\\   ~~~~`---.___.-~~
#              ______-==|                         | |  \\           _-~`
#        __--~~~  ,-/-==\\                        | |   `\        ,'
#     _-~       /'    |  \\                      / /      \      /
#   .'        /       |   \\                   /' /        \   /'
#  /  ____  /         |    \`\.__/-~~ ~ \ _ _/'  /          \/'
# /-'~    ~~~~~---__  |     ~-/~         ( )   /'        _--~`
#                   \_|      /        _)   ;  ),   __--~~
#                     '~~--_/      _-~/-  / \   '-~ \
#                    {\__--_/}    / \\_>- )<__\      \
#                    /'   (_/  _-~  | |__>--<__|      | 
#                   |0  0 _/) )-~     | |__>--<__|      |
#                   / /~ ,_/       / /__>---<__/      |
#                  o o _//        /-~_>---<__-~      /
#                  (^(~          /~_>---<__-      _-~
#                 ,/|           /__>--<__/     _-~
#              ,//('(          |__>--<__|     /                  .----_ 
#             ( ( '))          |__>--<__|    |                 /' _---_~\
#          `-)) )) (           |__>--<__|    |               /'  /     ~\`\
#         ,/,'//( (             \__>--<__\    \            /'  //        ||
#       ,( ( ((, ))              ~-__>--<_~-_  ~--____---~' _/'/        /'
#     `~/  )` ) ,/|                 ~-_~>--<_/-__       __-~ _/ 
#   ._-~//( )/ )) `                    ~~-'_/_/ /~~~~~~~__--~ 
#    ;'( ')/ ,)(                              ~~~~~~~~~~ 
#   ' ') '( (/
#     '   '  `


# fun game: find all the 👻's in the source code
# There is currently: 2 👻 (other than these 2)
# If you add a ghost please hide it well
# And don't use cmd+f/ctrl+f to find them, thats lame 👎

# TODO: (* = important/fix soon, - = a must have for release)
#
# 	*	add more items that are useful
# 	-	add ability to "inspect/look item"
# 	-	make better names && descriptions for rooms
# 	-	make function that replaces stuff like east with e
# 	-	have at least 50 different rooms
# 	-	make the forest more maze like
# 	-	make current_room a propert of player, not delegate
# 	-	add ability so save game
# 	 	add tests
# 		make the current tests check the description for directions
# 		add some kind of plot
# 		add a readme

# AND DON'T YOU DARE USE SPACES FOR TABS IN MY CODE
# http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/

require "readline"

def prompt(_prompt = "")
	Readline.readline(_prompt, true).squeeze(" ").strip.downcase
end

require_relative 'lib/colors'
require_relative 'lib/item'
require_relative 'lib/room'
require_relative 'lib/room_list'
require_relative 'lib/player'
require_relative 'lib/delegate'

delegate = Delegate.new

chance = 1000 
puts "Theres a 1 in #{chance} that this will be printed." \
	if rand(1..chance) == 1

loop do
	💬 = prompt("> ")
	delegate.parse(💬)
end
