#!/usr/bin/env ruby

# theres needs to be a dragon in the game
#        .==.        .==.       
#       //`^\\      //^`\\      
#      // ^ ^\(\__/)/^ ^^\\     
#     //^ ^^ ^/6  6\ ^^ ^ \\    
#    //^ ^^ ^/( .. )\^ ^ ^ \\   
#   // ^^ ^/\| v""v |/\^ ^ ^\\  
#  // ^^/\/ /  `~~`  \ \/\^ ^\\ 

# fun game: find all the 👻's in the source code
# There is currently: 1 👻 (other than these 2)
# If you add a ghost please hide it well
# And don't use cmd+f/ctrl+f to find them, thats lame 👎

# TODO:
# 	make better names && descriptions for rooms
# 	make function that replaces stuff like east with e
# 	stop wasting time

# AND DON'T YOU DARE USE SPACES FOR TABS IN MY CODE
# http://lea.verou.me/2012/01/why-tabs-are-clearly-superior/

require "readline"

def prompt(_prompt="")
	Readline.readline(_prompt, true).squeeze(" ").strip.downcase
end

require_relative 'lib/delegate'

delegate = Delegate.new

loop do
	💬 = prompt("> ")
	delegate.parse(💬)
end
