#!/usr/bin/env ruby

require 'minitest/autorun'

require_relative '../lib/item'
require_relative '../lib/room'
require_relative '../lib/room_list'

class Room
	attr_accessor :paths
end

describe RoomList do
	describe "rooms have correct paths" do
		it "must work" do
		
			rooms = RoomList.room_list
			rooms.each do |key, room|
				room.paths.each do |dir, place|
					other_dir = { n: :s, e: :w, s: :n, w: :e }[dir]
					new_room = rooms[place][other_dir]
					assert_equal new_room, key
				end
			end

		end
	end
end
